spring:
  # 数据源
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/v6blog
    username: v6blog
    password: ${POSTGRESQL_PASSWORD}
    hikari:
      maximum-pool-size: 20    # 8C16T
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      username: v6blog
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

